export const SET_PURCHASE_NOTE_COUNT = 'SET_PURCHASE_NOTE_COUNT'

export const SET_TENDER_COUNT = 'SET_TENDER_COUNT'

export const SET_RECEIVING_COUNT = 'SET_RECEIVING_COUNT'

export const SET_S_ORDER_COUNT_DATA = 'SET_S_ORDER_COUNT_DATA'

export const SET_S_ORDER_PRICE_DATA = 'SET_S_ORDER_PRICE_DATA'

export const SUB_S_ORDER_COUNT_DATA = 'SUB_S_ORDER_COUNT_DATA'

export const ADD_S_ORDER_PRICE_DATA = 'ADD_S_ORDER_PRICE_DATA'

export const CHANGE_IS_SHOW_ECHARTS = 'CHANGE_IS_SHOW_ECHARTS'

export const CHANGE_CHECKING_ROUTE = 'CHANGE_CHECKING_ROUTE'
